[build]
  command = """
    mkdir -p dist && \
    cp index.html dist/ && \
    cp -r scripts dist/ && \
    cp -r styles dist/ && \
    cp -r assets dist/
  """
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval';" 